import { adminConfig } from "./config.js";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

/* 接続前でも管理画面の見た目を確認できるようにする簡易サンプルデータ */
const sampleWorks = [
  {
    id: "sample-001",
    title: "ビジネス系YouTubeサムネイル",
    status: "published",
    source_type: "self_made",
    genre: "business",
    genreLabel: "ビジネス",
    thumbnail_image_url: "../assets/images/works/thumb/work-001.svg"
  },
  {
    id: "sample-002",
    title: "料理系レシピサムネイル",
    status: "draft",
    source_type: "trace",
    genre: "cooking",
    genreLabel: "料理",
    thumbnail_image_url: "../assets/images/works/thumb/work-005.svg"
  }
];

const selectors = {
  authStatus: document.querySelector("[data-auth-status]"),
  authView: document.querySelector("[data-auth-view]"),
  appView: document.querySelector("[data-app-view]"),
  authForm: document.querySelector("[data-auth-form]"),
  signOut: document.querySelector("[data-sign-out]"),
  workList: document.querySelector("[data-work-list]"),
  workForm: document.querySelector("[data-work-form]"),
  resetForm: document.querySelector("[data-reset-form]"),
  formMessage: document.querySelector("[data-form-message]"),
  genreForm: document.querySelector("[data-genre-form]"),
  genreMessage: document.querySelector("[data-genre-message]"),
  genreList: document.querySelector("[data-genre-list]"),
  genreSelects: document.querySelectorAll("[data-genre-select]"),
  workPreview: document.querySelector("[data-work-preview]"),
  editModal: document.querySelector("[data-edit-modal]"),
  editModalBody: document.querySelector("[data-edit-modal-body]")
};

let supabase = null;
let loadedWorks = [];
let genreMap = new Map();
let slugWasAutoGenerated = true;
let editingModalWorkId = null;

/* 初期表示時に UI バインドと Supabase 接続復元をまとめて実行 */
bootstrap();

async function bootstrap() {
  renderWorkList(sampleWorks);
  bindPreview(selectors.workForm?.elements.namedItem("work_image"), selectors.workPreview);
  bindFormReset();
  bindSlugAutomation();
  bindWorkSave();
  bindGenreCreate();
  bindEditModal();

  try {
    validateConfig(adminConfig);
    supabase = createClient(adminConfig.supabaseUrl, adminConfig.supabaseAnonKey);
    await restoreSession();
    await loadGenres();
    await loadWorks();
  } catch (error) {
    setAuthStatus("設定未完了", true);
    console.info("Admin config is not ready yet.", error);
  }

  bindAuth();
}

/* 管理画面に必要な接続設定が入っているか確認 */
function validateConfig(config) {
  if (!config.supabaseUrl || config.supabaseUrl.includes("YOUR_PROJECT")) {
    throw new Error("Supabase URL is not configured.");
  }

  if (!config.supabaseAnonKey || config.supabaseAnonKey.includes("YOUR_SUPABASE_ANON_KEY")) {
    throw new Error("Supabase anon key is not configured.");
  }
}

/* ログイン / ログアウト処理を登録 */
function bindAuth() {
  selectors.authForm?.addEventListener("submit", async (event) => {
    event.preventDefault();

    if (!supabase) {
      alert("config.js に Supabase の接続情報を設定してください。");
      return;
    }

    const formData = new FormData(event.currentTarget);
    const email = formData.get("email");
    const password = formData.get("password");

    if (!email || !password) {
      alert("メールアドレスとパスワードを入力してください。");
      return;
    }

    const { error } = await supabase.auth.signInWithPassword({ email, password });

    if (error) {
      alert(`ログインに失敗しました: ${error.message}`);
      return;
    }

    setAuthStatus("ログイン済み");
    setViewState(true);
    await loadWorks();
  });

  selectors.signOut?.addEventListener("click", async () => {
    if (!supabase) {
      return;
    }

    await supabase.auth.signOut();
    setAuthStatus("未ログイン");
    setViewState(false);
    renderWorkList(sampleWorks);
  });
}

/* 既存セッションを復元してログイン状態を反映 */
async function restoreSession() {
  const { data } = await supabase.auth.getSession();
  const isLoggedIn = Boolean(data.session);
  setAuthStatus(isLoggedIn ? "ログイン済み" : "未ログイン");
  setViewState(isLoggedIn);
}

/* 作品一覧を Supabase から取得して、管理画面表示用に整形 */
async function loadWorks() {
  if (!supabase) {
    return;
  }

  const { data, error } = await supabase
    .from(adminConfig.worksTable)
    .select(`
      id,
      title,
      slug,
      description,
      production_time,
      persona,
      purpose,
      design_point,
      tools,
      status,
      source_type,
      featured,
      sort_order,
      created_at,
      thumbnail_image_url,
      large_image_url,
      work_genres (
        genre_id,
        genres (
          slug,
          label
        )
      )
    `)
    .order("sort_order", { ascending: true })
    .order("created_at", { ascending: true });

  if (error) {
    console.error(error);
    alert(`作品一覧の取得に失敗しました: ${error.message}`);
    return;
  }

  loadedWorks = data.map((work) => ({
    ...work,
    genre: work.work_genres?.[0]?.genres?.slug ?? "",
    genreLabel: work.work_genres?.[0]?.genres?.label ?? "未設定"
  }));

  renderWorkList(loadedWorks);
  renderGenreList();
}

/* ジャンル一覧を読み込み、フォーム選択肢と管理一覧に反映 */
async function loadGenres() {
  if (!supabase) {
    return;
  }

  const { data, error } = await supabase
    .from(adminConfig.genresTable)
    .select("id, slug, label")
    .order("label", { ascending: true });

  if (error) {
    console.error(error);
    alert(`ジャンル一覧の取得に失敗しました: ${error.message}`);
    return;
  }

  genreMap = new Map((data || []).map((genre) => [genre.slug, genre]));
  renderGenreOptions();
  renderGenreList();
}

/* 新規作成フォームとモーダル内のジャンル選択肢を更新 */
function renderGenreOptions(selectedSlug = "") {
  const optionsMarkup = Array.from(genreMap.values()).map((genre) => `
    <option value="${escapeHtml(genre.slug)}" ${genre.slug === selectedSlug ? "selected" : ""}>${escapeHtml(genre.label)}</option>
  `).join("");

  selectors.genreSelects.forEach((select) => {
    if (!(select instanceof HTMLSelectElement)) {
      return;
    }

    const currentValue = selectedSlug || select.value;
    select.innerHTML = optionsMarkup;

    if (currentValue && genreMap.has(currentValue)) {
      select.value = currentValue;
    }
  });
}

/* ジャンル追加フォームを処理 */
function bindGenreCreate() {
  selectors.genreForm?.addEventListener("submit", async (event) => {
    event.preventDefault();

    if (!supabase) {
      setGenreMessage("Supabase 接続後にジャンル追加を有効化します。", true);
      return;
    }

    const formData = new FormData(event.currentTarget);
    const label = String(formData.get("genre_label") || "").trim();

    if (!label) {
      setGenreMessage("ジャンル名を入力してください。", true);
      return;
    }

    const slug = generateSlug(label);
    const duplicateLabel = Array.from(genreMap.values()).some((genre) => genre.label === label);

    if (duplicateLabel || genreMap.has(slug)) {
      setGenreMessage("同じジャンルがすでに登録されています。", true);
      return;
    }

    const { error } = await supabase
      .from(adminConfig.genresTable)
      .insert({
        slug,
        label
      });

    if (error) {
      console.error(error);
      setGenreMessage(`ジャンル追加に失敗しました: ${error.message}`, true);
      return;
    }

    await loadGenres();
    renderGenreOptions(slug);
    selectors.genreForm.reset();
    setGenreMessage(`「${label}」を追加しました。`);
  });
}

/* 登録済みジャンル一覧と削除ボタンを描画 */
function renderGenreList() {
  if (!selectors.genreList) {
    return;
  }

  const genres = Array.from(genreMap.values());

  selectors.genreList.innerHTML = genres.map((genre) => {
    const usageCount = loadedWorks.filter((work) => work.genre === genre.slug).length;
    return `
      <div class="admin-genre-item">
        <div class="admin-genre-item__content">
          <span class="admin-genre-item__label">${escapeHtml(genre.label)}</span>
          <span class="admin-genre-item__meta">${usageCount > 0 ? `${usageCount}件で使用中` : "未使用"}</span>
        </div>
        <div class="admin-genre-item__actions">
          <button class="admin-genre-item__delete" type="button" data-genre-delete="${escapeHtml(genre.slug)}">削除</button>
        </div>
      </div>
    `;
  }).join("");

  selectors.genreList.querySelectorAll("[data-genre-delete]").forEach((button) => {
    button.addEventListener("click", async () => {
      await deleteGenre(button.dataset.genreDelete || "");
    });
  });
}

/* 使われている作品数も踏まえてジャンルを削除 */
async function deleteGenre(genreSlug) {
  if (!supabase || !genreSlug) {
    return;
  }

  const genre = genreMap.get(genreSlug);
  if (!genre) {
    return;
  }

  const usageCount = loadedWorks.filter((work) => work.genre === genreSlug).length;
  const message = usageCount > 0
    ? `「${genre.label}」を削除しますか？ ${usageCount}件の作品からこのジャンル指定も外れます。`
    : `「${genre.label}」を削除しますか？`;

  if (!window.confirm(message)) {
    return;
  }

  const { error } = await supabase
    .from(adminConfig.genresTable)
    .delete()
    .eq("slug", genreSlug);

  if (error) {
    console.error(error);
    setGenreMessage(`ジャンル削除に失敗しました: ${error.message}`, true);
    return;
  }

  await loadGenres();
  await loadWorks();
  setGenreMessage(`「${genre.label}」を削除しました。`);
}

/* 作品カード一覧を描画し、カード内アクションを割り当てる */
function renderWorkList(works) {
  if (!selectors.workList) {
    return;
  }

  selectors.workList.innerHTML = works.map((work) => `
    <article class="admin-work-item admin-work-item--${work.status === "published" ? "published" : "draft"}" data-work-id="${escapeHtml(work.id)}">
      <div class="admin-work-item__thumb">
        ${work.thumbnail_image_url
          ? `<img src="${escapeHtml(work.thumbnail_image_url)}" alt="${escapeHtml(work.title)}">`
          : "画像未登録"}
      </div>
      <div class="admin-work-item__header">
        <h3 class="admin-work-item__title">${escapeHtml(work.title)}</h3>
        <span class="admin-work-item__status admin-work-item__status--${work.status === "published" ? "published" : "draft"}">
          ${escapeHtml(formatStatusLabel(work.status))}
        </span>
      </div>
      <p class="admin-work-item__meta">
        制作種別: ${escapeHtml(formatSourceTypeLabel(work.source_type))} / ジャンル: ${escapeHtml(work.genreLabel || "未設定")}
      </p>
      <div class="admin-work-item__actions">
        <button class="admin-work-item__button" type="button" data-action="edit" data-work-id="${escapeHtml(work.id)}">編集</button>
        <button class="admin-work-item__button" type="button" data-action="move-up" data-work-id="${escapeHtml(work.id)}">上へ</button>
        <button class="admin-work-item__button" type="button" data-action="move-down" data-work-id="${escapeHtml(work.id)}">下へ</button>
        <button class="admin-work-item__button" type="button" data-action="toggle-status" data-work-id="${escapeHtml(work.id)}">
          ${work.status === "published" ? "下書きに戻す" : "公開する"}
        </button>
        <button class="admin-work-item__button admin-work-item__button--danger" type="button" data-action="delete" data-work-id="${escapeHtml(work.id)}">削除</button>
      </div>
    </article>
  `).join("");

  selectors.workList.querySelectorAll("[data-action]").forEach((button) => {
    button.addEventListener("click", async (event) => {
      event.stopPropagation();
      const work = loadedWorks.find((entry) => entry.id === button.dataset.workId);
      if (!work) {
        return;
      }

      if (button.dataset.action === "edit") {
        openEditModal(work);
        return;
      }

      if (button.dataset.action === "move-up") {
        await moveWork(work.id, -1);
        return;
      }

      if (button.dataset.action === "move-down") {
        await moveWork(work.id, 1);
        return;
      }

      if (button.dataset.action === "toggle-status") {
        await toggleWorkStatus(work);
        return;
      }

      if (button.dataset.action === "delete") {
        await deleteWork(work);
      }
    });
  });

}

/* 新規追加フォームの画像プレビューを更新 */
function bindPreview(input, preview) {
  if (!(input instanceof HTMLInputElement) || !preview) {
    return;
  }

  input.addEventListener("change", async () => {
    const file = input.files?.[0];

    if (!file) {
      preview.textContent = "未選択";
      return;
    }

    await renderWatermarkedPreview(file, preview);
  });
}

/* 新規追加フォームを初期状態へ戻す */
function bindFormReset() {
  selectors.resetForm?.addEventListener("click", () => {
    selectors.workForm?.reset();
    const workIdField = selectors.workForm?.elements.namedItem("work_id");
    if (workIdField instanceof HTMLInputElement) {
      workIdField.value = "";
    }
    if (selectors.workPreview) {
      selectors.workPreview.textContent = "未選択";
    }
    const workImageField = selectors.workForm?.elements.namedItem("work_image");
    if (workImageField instanceof HTMLInputElement) {
      workImageField.required = true;
    }
    slugWasAutoGenerated = true;
    setFormMessage("新規作成モードに切り替えました。");
  });
}

/* 新規作品ではタイトルからスラッグを自動生成 */
function bindSlugAutomation() {
  const titleField = selectors.workForm?.elements.namedItem("title");
  const slugField = selectors.workForm?.elements.namedItem("slug");

  if (!(titleField instanceof HTMLInputElement) || !(slugField instanceof HTMLInputElement)) {
    return;
  }

  slugField.addEventListener("input", () => {
    slugWasAutoGenerated = slugField.value.trim() === "";
  });

  titleField.addEventListener("input", () => {
    const workIdField = selectors.workForm?.elements.namedItem("work_id");
    const isEditingExisting = workIdField instanceof HTMLInputElement && workIdField.value !== "";

    if (isEditingExisting || !slugWasAutoGenerated) {
      return;
    }

    slugField.value = generateSlug(titleField.value);
  });
}

/* 新規追加フォームから作品を保存 */
function bindWorkSave() {
  selectors.workForm?.addEventListener("submit", async (event) => {
    event.preventDefault();

    if (!supabase) {
      alert("UI は準備済みです。Supabase 接続後に保存処理を有効化します。");
      return;
    }

    const formData = new FormData(event.currentTarget);
    const workId = formData.get("work_id");
    const selectedGenre = String(formData.get("genre") || "");
    const existingWork = loadedWorks.find((work) => work.id === workId) || null;
    const nextFeatured = formData.get("featured") === "on";
    const imageUpload = await uploadWorkImage(formData, existingWork);

    if (imageUpload?.error) {
      console.error(imageUpload.error);
      setFormMessage(`画像の保存に失敗しました: ${imageUpload.error.message}`, true);
      return;
    }

    const payload = buildWorkPayload(formData, imageUpload?.urls ?? existingWork);

    if (!payload.title || !payload.slug || !payload.description) {
      setFormMessage("タイトル、スラッグ、短い説明は必須です。", true);
      return;
    }

    if (!payload.thumbnail_image_url) {
      setFormMessage("作品画像は必須です。画像を選択してから保存してください。", true);
      return;
    }

    if (!canSaveFeaturedWork(nextFeatured, workId)) {
      setFormMessage("ピックアップ作品は最大5件までです。別の作品のピックアップ表示を外してから保存してください。", true);
      return;
    }

    const query = workId
      ? supabase.from(adminConfig.worksTable).update(payload).eq("id", workId)
      : supabase.from(adminConfig.worksTable).insert(payload);

    const { data, error } = await query.select("id").single();

    if (error) {
      console.error(error);
      setFormMessage(`保存に失敗しました: ${error.message}`, true);
      return;
    }

    const savedWorkId = workId || data?.id;
    const genreError = await saveWorkGenre(savedWorkId, selectedGenre);

    if (genreError) {
      console.error(genreError);
      setFormMessage(`作品は保存されましたが、ジャンル保存に失敗しました: ${genreError.message}`, true);
      await loadWorks();
      return;
    }

    setFormMessage(workId ? "作品を更新しました。" : "作品を保存しました。");
    await loadWorks();
  });
}

/* フォーム値を Supabase 保存用の payload に変換 */
function buildWorkPayload(formData, imageData = null) {
  return {
    title: String(formData.get("title") || "").trim(),
    slug: String(formData.get("slug") || "").trim(),
    description: String(formData.get("description") || "").trim(),
    production_time: normalizeNullableText(formData.get("production_time")),
    persona: normalizeNullableText(formData.get("persona")),
    purpose: normalizeNullableText(formData.get("purpose")),
    design_point: normalizeNullableText(formData.get("design_point")),
    tools: parseTools(formData.get("tools")),
    status: String(formData.get("status") || "draft"),
    source_type: String(formData.get("source_type") || "self_made"),
    featured: formData.get("featured") === "on",
    sort_order: Number(formData.get("sort_order") || 0),
    thumbnail_image_url: imageData?.thumbnail_image_url ?? null,
    large_image_url: imageData?.large_image_url ?? imageData?.thumbnail_image_url ?? null
  };
}

/* 既存作品を下部フォームへ流し込むときの反映処理 */
function fillWorkForm(work) {
  if (!selectors.workForm) {
    return;
  }

  setFieldValue("work_id", work.id);
  setFieldValue("title", work.title);
  setFieldValue("slug", work.slug);
  setFieldValue("description", work.description);
  setFieldValue("production_time", work.production_time ?? "");
  setFieldValue("tools", (work.tools || []).join(", "));
  setFieldValue("persona", work.persona ?? "");
  setFieldValue("purpose", work.purpose ?? "");
  setFieldValue("design_point", work.design_point ?? "");
  setFieldValue("status", work.status);
  setFieldValue("source_type", work.source_type);
  setFieldValue("genre", work.genre || "business");
  setFieldValue("sort_order", String(work.sort_order ?? 0));
  setCheckboxValue("featured", Boolean(work.featured));
  slugWasAutoGenerated = false;
  if (selectors.workPreview) {
    selectors.workPreview.innerHTML = work.thumbnail_image_url
      ? `<img src="${escapeHtml(work.thumbnail_image_url)}" alt="${escapeHtml(work.title)}">`
      : "未選択";
  }
  const workImageField = selectors.workForm?.elements.namedItem("work_image");
  if (workImageField instanceof HTMLInputElement) {
    workImageField.required = !work.thumbnail_image_url;
  }
  setFormMessage(`「${work.title}」を編集中です。`);
}

/* 一覧から公開 / 下書き状態をワンクリックで切り替える */
async function toggleWorkStatus(work) {
  if (!supabase) {
    return;
  }

  const nextStatus = work.status === "published" ? "draft" : "published";
  const { error } = await supabase
    .from(adminConfig.worksTable)
    .update({ status: nextStatus })
    .eq("id", work.id);

  if (error) {
    console.error(error);
    setFormMessage(`公開状態の更新に失敗しました: ${error.message}`, true);
    return;
  }

  setFormMessage(`「${work.title}」を${nextStatus === "published" ? "公開" : "下書き"}に切り替えました。`);
  await loadWorks();
}

/* 作品を削除して、必要なら編集中フォームもリセット */
async function deleteWork(work) {
  if (!supabase) {
    return;
  }

  const confirmed = window.confirm(`「${work.title}」を削除しますか？`);
  if (!confirmed) {
    return;
  }

  const { error } = await supabase
    .from(adminConfig.worksTable)
    .delete()
    .eq("id", work.id);

  if (error) {
    console.error(error);
    setFormMessage(`削除に失敗しました: ${error.message}`, true);
    return;
  }

  const currentWorkId = selectors.workForm?.elements.namedItem("work_id");
  if (currentWorkId instanceof HTMLInputElement && currentWorkId.value === work.id) {
    selectors.resetForm?.click();
  }

  setFormMessage(`「${work.title}」を削除しました。`);
  await loadWorks();
}

/* 上へ / 下へ の操作に合わせて sort_order を振り直す */
async function moveWork(workId, direction) {
  if (!supabase) {
    return;
  }

  const currentIndex = loadedWorks.findIndex((work) => work.id === workId);
  const targetIndex = currentIndex + direction;

  if (currentIndex === -1 || targetIndex < 0 || targetIndex >= loadedWorks.length) {
    return;
  }

  const reorderedWorks = [...loadedWorks];
  const [movedWork] = reorderedWorks.splice(currentIndex, 1);
  reorderedWorks.splice(targetIndex, 0, movedWork);

  const updateResults = await Promise.all(reorderedWorks.map((work, index) => (
    supabase
      .from(adminConfig.worksTable)
      .update({ sort_order: index + 1 })
      .eq("id", work.id)
  )));

  const failedUpdate = updateResults.find((result) => result.error);
  if (failedUpdate?.error) {
    console.error(failedUpdate.error);
    setFormMessage(`並び順の更新に失敗しました: ${failedUpdate.error.message}`, true);
    return;
  }

  setFormMessage(`「${movedWork.title}」の並び順を更新しました。`);
  await loadWorks();
}

/* モーダル内の軽量編集フォームから既存作品を保存 */
async function saveInlineWork(formElement) {
  if (!(formElement instanceof HTMLFormElement) || !supabase) {
    return;
  }

  const formData = new FormData(formElement);
  const workId = String(formData.get("work_id") || "");
  const selectedGenre = String(formData.get("genre") || "");
  const nextFeatured = formData.get("featured") === "on";
  const existingWork = loadedWorks.find((work) => work.id === workId) || null;
  const imageUpload = await uploadWorkImage(formData, existingWork);

  if (imageUpload?.error) {
    console.error(imageUpload.error);
    setFormMessage(`画像の保存に失敗しました: ${imageUpload.error.message}`, true);
    return;
  }

  const payload = buildWorkPayload(formData, imageUpload?.urls ?? existingWork);

  if (!payload.title || !payload.slug || !payload.description) {
    setFormMessage("インライン編集でもタイトル、スラッグ、短い説明は必須です。", true);
    return;
  }

  if (!payload.thumbnail_image_url) {
    setFormMessage("作品画像は必須です。画像を選択してから保存してください。", true);
    return;
  }

  if (!canSaveFeaturedWork(nextFeatured, workId)) {
    setFormMessage("ピックアップ作品は最大5件までです。別の作品のピックアップ表示を外してから保存してください。", true);
    return;
  }

  const { error } = await supabase
    .from(adminConfig.worksTable)
    .update(payload)
    .eq("id", workId);

  if (error) {
    console.error(error);
    setFormMessage(`インライン保存に失敗しました: ${error.message}`, true);
    return;
  }

  const genreError = await saveWorkGenre(workId, selectedGenre);
  if (genreError) {
    console.error(genreError);
    setFormMessage(`作品は保存されましたが、ジャンル保存に失敗しました: ${genreError.message}`, true);
    await loadWorks();
    return;
  }

  editingModalWorkId = null;
  closeEditModal();
  setFormMessage("一覧カードから作品を更新しました。");
  await loadWorks();
}

/* 編集モーダルの開閉イベントをまとめて登録 */
function bindEditModal() {
  document.querySelectorAll("[data-edit-modal-close]").forEach((element) => {
    element.addEventListener("click", closeEditModal);
  });

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && selectors.editModal && !selectors.editModal.hidden) {
      closeEditModal();
    }
  });
}

/* 一覧カードの編集ボタンからモーダルを開く */
function openEditModal(work) {
  if (!selectors.editModal || !selectors.editModalBody) {
    return;
  }

  editingModalWorkId = work.id;
  selectors.editModalBody.innerHTML = `
    <div class="admin-modal__content">
      <div class="admin-modal__header">
        <div>
          <p class="admin-modal__eyebrow">Edit Work</p>
          <h2 class="admin-modal__title" id="edit-modal-title">「${escapeHtml(work.title)}」を編集</h2>
          <p class="admin-modal__text">既存作品の編集はこのポップアップで行います。</p>
        </div>
      </div>
      ${renderInlineEditor(work)}
    </div>
  `;

  selectors.editModal.hidden = false;
  document.body.style.overflow = "hidden";

  const form = selectors.editModalBody.querySelector("[data-inline-form]");
  form?.addEventListener("submit", async (event) => {
    event.preventDefault();
    await saveInlineWork(event.currentTarget);
  });

  selectors.editModalBody.querySelector("[data-inline-cancel]")?.addEventListener("click", closeEditModal);
  bindInlinePreview(form);
}

/* 編集モーダルを閉じて状態を初期化 */
function closeEditModal() {
  if (!selectors.editModal || !selectors.editModalBody) {
    return;
  }

  selectors.editModal.hidden = true;
  selectors.editModalBody.innerHTML = "";
  editingModalWorkId = null;
  document.body.style.overflow = "";
}

/* モーダル側の画像差し替えプレビューを更新 */
function bindInlinePreview(formElement) {
  const fileInput = formElement.querySelector('input[name="work_image"]');
  const preview = formElement.querySelector("[data-inline-preview]");

  if (!(fileInput instanceof HTMLInputElement) || !preview) {
    return;
  }

  fileInput.addEventListener("change", async () => {
    const file = fileInput.files?.[0];

    if (!file) {
      preview.innerHTML = preview.dataset.originalPreview || "画像未登録";
      return;
    }

    await renderWatermarkedPreview(file, preview);
  });
}

/* 画像を透かし入りでアップロードし、公開用URLを返す */
async function uploadWorkImage(formData, existingWork) {
  if (!supabase) {
    return null;
  }

  const file = formData.get("work_image");
  const slug = String(formData.get("slug") || "").trim();

  if (!(file instanceof File) || file.size === 0) {
    return {
      urls: existingWork
        ? {
            thumbnail_image_url: existingWork.thumbnail_image_url ?? null,
            large_image_url: existingWork.large_image_url ?? existingWork.thumbnail_image_url ?? null
          }
        : null
    };
  }

  const processedImage = await createSampleWatermarkedImage(file);

  if (processedImage.error) {
    return {
      error: processedImage.error
    };
  }

  const uploadFile = processedImage.file || file;
  const extension = extractExtension(uploadFile.name);
  const title = String(formData.get("title") || existingWork?.title || "").trim();
  const fileSlug = slug || existingWork?.slug || generateSlug(title) || "work";
  const filePath = `${fileSlug}-${Date.now()}.${extension}`;
  const bucketCandidates = getImageBucketCandidates();

  let uploadedBucket = "";
  let uploadError = null;

  for (const bucketName of bucketCandidates) {
    const result = await supabase.storage
      .from(bucketName)
      .upload(filePath, uploadFile, {
        cacheControl: "3600",
        upsert: true
      });

    if (!result.error) {
      uploadedBucket = bucketName;
      uploadError = null;
      break;
    }

    uploadError = result.error;

    if (!result.error.message.toLowerCase().includes("bucket")) {
      break;
    }
  }

  if (uploadError || !uploadedBucket) {
    return {
      error: uploadError || new Error(`画像保存先のバケットが見つかりません: ${bucketCandidates.join(", ")}`)
    };
  }

  const { data } = supabase.storage
    .from(uploadedBucket)
    .getPublicUrl(filePath);

  return {
    urls: {
      thumbnail_image_url: data.publicUrl,
      large_image_url: data.publicUrl
    }
  };
}

/* 画像に SAMPLE を焼き込んだファイルとプレビューURLを作る */
async function createSampleWatermarkedImage(file) {
  try {
    const image = await loadImageFromFile(file);
    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");

    if (!context) {
      throw new Error("画像加工用のCanvasコンテキストが取得できませんでした。");
    }

    canvas.width = image.naturalWidth || image.width;
    canvas.height = image.naturalHeight || image.height;

    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    drawSampleWatermark(context, canvas.width, canvas.height);

    const mimeType = normalizeImageMimeType(file.type);
    const blob = await canvasToBlob(canvas, mimeType, mimeType === "image/jpeg" ? 0.92 : undefined);
    const previewUrl = canvas.toDataURL(mimeType, mimeType === "image/jpeg" ? 0.92 : undefined);

    const nextExtension = mimeType === "image/png" ? "png" : "jpg";
    const baseName = file.name.replace(/\.[^.]+$/, "") || `work-${Date.now()}`;

    return {
      file: new File([blob], `${baseName}.${nextExtension}`, { type: mimeType }),
      previewUrl
    };
  } catch (error) {
    return {
      error: error instanceof Error ? error : new Error("画像加工に失敗しました。")
    };
  }
}

/* 保存前プレビューにも焼き込み後画像を表示 */
async function renderWatermarkedPreview(file, preview) {
  const processedImage = await createSampleWatermarkedImage(file);

  if (processedImage.error) {
    preview.textContent = `プレビュー生成に失敗しました: ${processedImage.error.message}`;
    return;
  }

  preview.innerHTML = `<img src="${processedImage.previewUrl}" alt="${escapeHtml(file.name)}">`;
}

/* FileReader で画像を読み込み、Image オブジェクトへ変換 */
function loadImageFromFile(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => {
      const image = new Image();
      image.onload = () => resolve(image);
      image.onerror = () => reject(new Error("画像の読み込みに失敗しました。"));
      image.src = String(reader.result || "");
    };

    reader.onerror = () => reject(new Error("画像ファイルの読み込みに失敗しました。"));
    reader.readAsDataURL(file);
  });
}

/* 公開画像に焼き込む SAMPLE 透かしを描画 */
function drawSampleWatermark(context, width, height) {
  const fontSize = Math.max(40, Math.min(width, height) * 0.12);

  context.save();
  context.translate(width / 2, height / 2);
  context.rotate((-18 * Math.PI) / 180);

  context.textAlign = "center";
  context.textBaseline = "middle";
  context.font = `800 ${fontSize}px sans-serif`;
  context.lineJoin = "round";
  context.strokeStyle = "rgba(0, 0, 0, 0.22)";
  context.lineWidth = Math.max(6, fontSize * 0.08);
  context.strokeText("SAMPLE", 0, 0);
  context.fillStyle = "rgba(255, 255, 255, 0.72)";
  context.fillText("SAMPLE", 0, 0);

  context.restore();
}

/* 画像形式の扱いを jpg / png に寄せて正規化 */
function normalizeImageMimeType(mimeType) {
  if (mimeType === "image/png") {
    return "image/png";
  }

  return "image/jpeg";
}

/* canvas からアップロード可能な Blob を生成 */
function canvasToBlob(canvas, mimeType, quality) {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) {
        reject(new Error("画像の書き出しに失敗しました。"));
        return;
      }

      resolve(blob);
    }, mimeType, quality);
  });
}

/* 既存環境差を吸収するため、画像用 bucket 候補を順に返す */
function getImageBucketCandidates() {
  return [...new Set([
    adminConfig.thumbnailsBucket,
    adminConfig.largeImagesBucket,
    "work-thumbnails",
    "work-large"
  ].filter(Boolean))];
}

/* 作品とジャンルの中間テーブルを更新 */
async function saveWorkGenre(workId, genreSlug) {
  if (!supabase || !workId || !genreSlug) {
    return null;
  }

  const genre = genreMap.get(genreSlug);

  if (!genre) {
    return new Error(`Unknown genre slug: ${genreSlug}`);
  }

  const { error: deleteError } = await supabase
    .from(adminConfig.workGenresTable)
    .delete()
    .eq("work_id", workId);

  if (deleteError) {
    return deleteError;
  }

  const { error: insertError } = await supabase
    .from(adminConfig.workGenresTable)
    .insert({
      work_id: workId,
      genre_id: genre.id
    });

  return insertError;
}

/* 下部フォームの入力値セット用ヘルパー */
function setFieldValue(name, value) {
  const field = selectors.workForm?.elements.namedItem(name);
  if (
    field instanceof HTMLInputElement ||
    field instanceof HTMLTextAreaElement ||
    field instanceof HTMLSelectElement
  ) {
    field.value = value;
  }
}

/* 下部フォームのチェックボックス反映用ヘルパー */
function setCheckboxValue(name, checked) {
  const field = selectors.workForm?.elements.namedItem(name);
  if (field instanceof HTMLInputElement) {
    field.checked = checked;
  }
}

/* ジャンル管理用メッセージを表示 */
function setGenreMessage(message, isError = false) {
  if (!selectors.genreMessage) {
    return;
  }

  selectors.genreMessage.textContent = message;
  selectors.genreMessage.style.color = isError ? "#b42318" : "var(--admin-muted)";
}

/* 新規追加 / 編集のメッセージを表示 */
function setFormMessage(message, isError = false) {
  if (!selectors.formMessage) {
    return;
  }

  selectors.formMessage.textContent = message;
  selectors.formMessage.style.color = isError ? "#b42318" : "var(--admin-muted)";
}

/* 空文字を null に揃えて保存しやすくする */
function normalizeNullableText(value) {
  const normalized = String(value || "").trim();
  return normalized || null;
}

/* カンマ区切りのツール名を配列化 */
function parseTools(value) {
  return String(value || "")
    .split(",")
    .map((tool) => tool.trim())
    .filter(Boolean);
}

/* タイトルなどから URL 用スラッグを作る */
function generateSlug(title) {
  const normalized = String(title || "")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-");

  if (normalized) {
    return normalized;
  }

  return `work-${Date.now()}`;
}

/* ファイル名から拡張子を抽出 */
function extractExtension(filename) {
  const match = String(filename || "").match(/\.([a-zA-Z0-9]+)$/);
  return match ? match[1].toLowerCase() : "jpg";
}

/* ピックアップ作品が最大5件を超えないか判定 */
function canSaveFeaturedWork(nextFeatured, editingWorkId) {
  if (!nextFeatured) {
    return true;
  }

  const featuredCount = loadedWorks.filter((work) => work.featured && work.id !== editingWorkId).length;
  return featuredCount < 5;
}

/* モーダル内で使う既存作品のインライン編集フォームを組み立てる */
function renderInlineEditor(work) {
  const previewMarkup = work.thumbnail_image_url
    ? `<img src="${escapeHtml(work.thumbnail_image_url)}" alt="${escapeHtml(work.title)}">`
    : "画像未登録";
  const featuredLimitReached = !work.featured && !canSaveFeaturedWork(true, work.id);

  return `
    <form class="admin-work-item__inline-form" data-inline-form>
      <input type="hidden" name="work_id" value="${escapeHtml(work.id)}">
      <div class="admin-work-item__inline-grid">
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">タイトル <span class="admin-field__meta admin-field__meta--required">必須</span></span>
          <input class="admin-work-item__control" type="text" name="title" value="${escapeHtml(work.title)}">
        </label>
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">スラッグ <span class="admin-field__meta admin-field__meta--required">必須</span></span>
          <input class="admin-work-item__control" type="text" name="slug" value="${escapeHtml(work.slug)}">
        </label>
      </div>
      <div class="admin-work-item__inline-grid">
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">状態 <span class="admin-field__meta admin-field__meta--required">必須</span></span>
          <select class="admin-work-item__control" name="status">
            <option value="draft" ${work.status === "draft" ? "selected" : ""}>下書き</option>
            <option value="published" ${work.status === "published" ? "selected" : ""}>公開</option>
          </select>
        </label>
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">制作種別 <span class="admin-field__meta admin-field__meta--required">必須</span></span>
          <select class="admin-work-item__control" name="source_type">
            <option value="self_made" ${work.source_type === "self_made" ? "selected" : ""}>自主制作</option>
            <option value="trace" ${work.source_type === "trace" ? "selected" : ""}>トレース</option>
          </select>
        </label>
      </div>
      <div class="admin-work-item__inline-grid">
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">ジャンル <span class="admin-field__meta admin-field__meta--required">必須</span></span>
          <select class="admin-work-item__control" name="genre" data-genre-select>
            ${Array.from(genreMap.values()).map((genre) => `
              <option value="${escapeHtml(genre.slug)}" ${work.genre === genre.slug ? "selected" : ""}>${escapeHtml(genre.label)}</option>
            `).join("")}
          </select>
        </label>
        <label class="admin-work-item__field">
          <span class="admin-work-item__label">並び順 <span class="admin-field__meta admin-field__meta--optional">任意</span></span>
          <input class="admin-work-item__control" type="number" name="sort_order" min="0" step="1" value="${escapeHtml(String(work.sort_order ?? 0))}">
        </label>
      </div>
      <label class="admin-work-item__field">
        <span class="admin-work-item__label">短い説明 <span class="admin-field__meta admin-field__meta--required">必須</span></span>
        <textarea class="admin-work-item__control admin-work-item__control--textarea" rows="3" name="description">${escapeHtml(work.description ?? "")}</textarea>
      </label>
      <label class="admin-work-item__field">
        <span class="admin-work-item__label">画像を差し替え <span class="admin-field__meta ${work.thumbnail_image_url ? "admin-field__meta--optional" : "admin-field__meta--required"}">${work.thumbnail_image_url ? "任意" : "必須"}</span></span>
        <input class="admin-work-item__control" type="file" name="work_image" accept="image/*" ${work.thumbnail_image_url ? "" : "required"}>
      </label>
      <div class="admin-work-item__preview" data-inline-preview data-original-preview="${escapeHtml(previewMarkup)}">
        ${previewMarkup}
      </div>
      <div class="admin-work-item__checkboxes">
        <label class="admin-work-item__check">
          <input type="checkbox" name="featured" ${work.featured ? "checked" : ""} ${featuredLimitReached ? "disabled" : ""}>
          <span>ピックアップ表示</span>
        </label>
      </div>
      ${featuredLimitReached ? `<p class="admin-work-item__hint">ピックアップ作品は現在5件です。別の作品のピックアップ表示を外すと選択できます。</p>` : ""}
      <div class="admin-work-item__actions">
        <button class="admin-work-item__button" type="submit">保存</button>
        <button class="admin-work-item__button" type="button" data-inline-cancel>キャンセル</button>
      </div>
    </form>
  `;
}

function formatStatusLabel(status) {
  if (status === "published") {
    return "公開中";
  }

  if (status === "draft") {
    return "下書き";
  }

  return status;
}

function formatSourceTypeLabel(sourceType) {
  if (sourceType === "self_made") {
    return "自主制作";
  }

  if (sourceType === "trace") {
    return "トレース";
  }

  return sourceType;
}

function setAuthStatus(label, muted = false) {
  if (!selectors.authStatus) {
    return;
  }

  selectors.authStatus.textContent = label;
  selectors.authStatus.style.color = muted ? "var(--admin-muted)" : "var(--admin-accent)";
}

function setViewState(isLoggedIn) {
  if (selectors.authView) {
    selectors.authView.hidden = isLoggedIn;
  }

  if (selectors.appView) {
    selectors.appView.hidden = !isLoggedIn;
  }

  if (selectors.signOut) {
    selectors.signOut.hidden = !isLoggedIn;
  }
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
